### ISSUE TITLE
Can not build on Kwin 5.21

### ISSUE THREAD

**Issue by hillwoodroc** [ukui/ukui-kwin#42]
/mocs_compilation.cpp:7:
[  132s] /home/abuild/rpmbuild/BUILD/ukui-kwin-274ca9a227dfbdf43625d02e054de8240740586c/build/kcmkwin/kwindecoration/declarative-plugin/kdecorationprivatedeclarative_autogen/EWIEGA46WW/../../../../../../kcmkwin/kwindecoration/declarative-plugin/previewclient.h:110:10: error: 'void KDecoration2::Preview::PreviewClient::requestShowWindowMenu()' marked 'override', but does not override
[  132s]   110 |     void requestShowWindowMenu() override;
[  132s]       |          ^~~~~~~~~~~~~~~~~~~~~
[  132s] make[2]: *** [kcmkwin/kwindecoration/declarative-plugin/CMakeFiles/kdecorationprivatedeclarative.dir/build.make:82: kcmkwin/kwindecoration/declarative-plugin/CMakeFiles/kdecorationprivatedeclarative.dir/kdecorationprivatedeclarative_autogen/mocs_compilation.cpp.o] Error 1
[  132s] make[2]: Leaving directory '/home/abuild/rpmbuild

/BUILD/ukui-kwin-274ca9a227dfbdf43625d02e054de8240740586c/build'
[  132s] make[1]: *** [CMakeFiles/Makefile2:2793: kcmkwin/kwindecoration/declarative-plugin/CMakeFiles/kdecorationprivatedeclarative.dir/all] Error 2
[  132s] make[1]: *** Waiting for unfinished jobs....

**Comment by OriPoin** [comment]
我也遇到了同样的错误，请看下这次[commit](https://github.com/KDE/kdecoration/commit/fac2422565f62136e474b940733466d2f6cf8fc7#diff-dc25d8fba1b0daf0953d3f17f3d360c41cf1002e0d51dfc6267c77ed7ada0199)。
5.20.90后完善了requestShowWindowMenu函数，导致ukui-kwin在override这个函数的时候输入不一致

**Comment by OriPoin** [comment]
可以使用这个[patch](https://github.com/ukui/ukui-overlay/blob/master/x11-wm/ukui-kwin/files/requestShowWindowMenu_deprecated.patch)
